"""update tier tables

Revision ID: 54886fb5ef74
Revises: 6194a23286d4
Create Date: 2026-08-01 15:43:00.543617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54886fb5ef74'
down_revision: Union[str, Sequence[str], None] = '6194a23286d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiers', sa.Column('link_durability', sa.String(length=50), nullable=True))
    op.add_column('tiers', sa.Column('max_custom_domains', sa.Integer(), nullable=True))
    op.add_column('tiers', sa.Column('max_onyx_subdomains', sa.Integer(), nullable=True))
    op.add_column('tiers', sa.Column('max_custom_paths', sa.Integer(), nullable=True))
    op.add_column('tiers', sa.Column('max_visits_per_shortlink', sa.Integer(), nullable=True))
    op.add_column('tiers', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('tiers', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('tiers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiers', 'deleted_at')
    op.drop_column('tiers', 'deleted')
    op.drop_column('tiers', 'features')
    op.drop_column('tiers', 'max_visits_per_shortlink')
    op.drop_column('tiers', 'max_custom_paths')
    op.drop_column('tiers', 'max_onyx_subdomains')
    op.drop_column('tiers', 'max_custom_domains')
    op.drop_column('tiers', 'link_durability')
    # ### end Alembic commands ###
