"""update tier tables

Revision ID: 59deb2a3334b
Revises: 54886fb5ef74
Create Date: 2026-08-01 15:45:49.052715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59deb2a3334b'
down_revision: Union[str, Sequence[str], None] = '54886fb5ef74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tiers', 'max_short_link',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tiers', 'max_custom_domains',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('tiers', 'max_onyx_subdomains',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('tiers', 'max_custom_paths',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('tiers', 'max_visits_per_shortlink',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tiers', 'max_visits_per_shortlink',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tiers', 'max_custom_paths',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('tiers', 'max_onyx_subdomains',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('tiers', 'max_custom_domains',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('tiers', 'max_short_link',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
