"""qu_image column added to redirect

Revision ID: 658c98eaca7b
Revises: a02d3ca050fd
Create Date: 2026-07-31 21:48:20.359963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658c98eaca7b'
down_revision: Union[str, Sequence[str], None] = 'a02d3ca050fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redirects', sa.Column('qr_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redirects', 'qr_image')
    # ### end Alembic commands ###
