"""description column added to tier

Revision ID: a57ddda9f85c
Revises: ecc35cf6386f
Create Date: 2026-08-01 15:15:33.645204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57ddda9f85c'
down_revision: Union[str, Sequence[str], None] = 'ecc35cf6386f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiers', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiers', 'description')
    # ### end Alembic commands ###
