"""admin column added to user

Revision ID: a96307e3432c
Revises: 658c98eaca7b
Create Date: 2026-08-01 14:28:13.873174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96307e3432c'
down_revision: Union[str, Sequence[str], None] = '658c98eaca7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redirects_slug'), table_name='redirects')
    op.create_index(op.f('ix_redirects_slug'), 'redirects', ['slug'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('admin_priviledges', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_priviledges')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_redirects_slug'), table_name='redirects')
    op.create_index(op.f('ix_redirects_slug'), 'redirects', ['slug'], unique=True)
    # ### end Alembic commands ###
