"""update user table add paystack customer id

Revision ID: c1b8f3a5816c
Revises: e2731552ae93
Create Date: 2026-08-01 17:36:32.957774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b8f3a5816c'
down_revision: Union[str, Sequence[str], None] = 'e2731552ae93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paystack_customer_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['paystack_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'paystack_customer_id')
    # ### end Alembic commands ###
