"""database migration - initial

Revision ID: d346b1a470a4
Revises: 
Create Date: 2026-08-03 12:32:36.656124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd346b1a470a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('paystack_plan_code', sa.String(length=50), nullable=True),
    sa.Column('max_short_link', sa.String(length=50), nullable=False),
    sa.Column('link_durability', sa.String(length=50), nullable=True),
    sa.Column('max_custom_domains', sa.String(length=50), nullable=False),
    sa.Column('max_onyx_subdomains', sa.String(length=50), nullable=False),
    sa.Column('max_custom_paths', sa.String(length=50), nullable=False),
    sa.Column('max_visits_per_shortlink', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tiers_tier_id'), 'tiers', ['tier_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('paystack_customer_id', sa.String(length=50), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('admin_priviledges', sa.JSON(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'TERMINATED', 'DELETED', name='user_status'), nullable=False),
    sa.Column('current_sub_id', sa.UUID(), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paystack_customer_id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'UNPAID', 'TRAILING', 'PAST_DUE', 'CANCELLED', name='subscription_status'), nullable=False),
    sa.Column('idompotent_key', sa.UUID(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('paystack_subscription_code', sa.String(length=50), nullable=True),
    sa.Column('paystack_email_token', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.tier_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_idompotent_key'), 'subscriptions', ['idompotent_key'], unique=True)
    op.create_index(op.f('ix_subscriptions_sub_id'), 'subscriptions', ['sub_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_tier_id'), 'subscriptions', ['tier_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('txt_verified', sa.Boolean(), nullable=False),
    sa.Column('cname_verified', sa.Boolean(), nullable=False),
    sa.Column('txt_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_index(op.f('ix_domains_user_id'), 'domains', ['user_id'], unique=False)
    op.create_table('redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redirect_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('qr_image', sa.String(length=255), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('expired_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'slug', name='idx_domain_slug')
    )
    op.create_index(op.f('ix_redirects_redirect_id'), 'redirects', ['redirect_id'], unique=True)
    op.create_index(op.f('ix_redirects_slug'), 'redirects', ['slug'], unique=False)
    op.create_index(op.f('ix_redirects_user_id'), 'redirects', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('redirect_visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redirect_id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['redirect_id'], ['redirects.redirect_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redirect_visitors')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_redirects_user_id'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_slug'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_redirect_id'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_domains_user_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tiers_tier_id'), table_name='tiers')
    op.drop_table('tiers')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tier_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_sub_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_idompotent_key'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
