"""add paystack fields to tier and subscription

Revision ID: f32fbc2bdb97
Revises: c1b8f3a5816c
Create Date: 2026-08-01 17:47:58.911706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32fbc2bdb97'
down_revision: Union[str, Sequence[str], None] = 'c1b8f3a5816c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('paystack_subscription_code', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('paystack_email_token', sa.String(length=50), nullable=True))
    op.add_column('tiers', sa.Column('paystack_plan_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiers', 'paystack_plan_code')
    op.drop_column('subscriptions', 'paystack_email_token')
    op.drop_column('subscriptions', 'paystack_subscription_code')
    # ### end Alembic commands ###
